// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Authenticate.proto
// Protobuf C++ Version: 5.28.2

#include "Authenticate.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace GaoProtobuf {

inline constexpr AuthenticateResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : requestid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        result_{static_cast< ::GaoProtobuf::AuthenticationResult >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AuthenticateResponse::AuthenticateResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AuthenticateResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthenticateResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthenticateResponseDefaultTypeInternal() {}
  union {
    AuthenticateResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthenticateResponseDefaultTypeInternal _AuthenticateResponse_default_instance_;

inline constexpr AuthenticateRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        requestid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AuthenticateRequest::AuthenticateRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AuthenticateRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthenticateRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthenticateRequestDefaultTypeInternal() {}
  union {
    AuthenticateRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthenticateRequestDefaultTypeInternal _AuthenticateRequest_default_instance_;
}  // namespace GaoProtobuf
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Authenticate_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Authenticate_2eproto = nullptr;
const ::uint32_t
    TableStruct_Authenticate_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GaoProtobuf::AuthenticateRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GaoProtobuf::AuthenticateRequest, _impl_.token_),
        PROTOBUF_FIELD_OFFSET(::GaoProtobuf::AuthenticateRequest, _impl_.requestid_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GaoProtobuf::AuthenticateResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GaoProtobuf::AuthenticateResponse, _impl_.result_),
        PROTOBUF_FIELD_OFFSET(::GaoProtobuf::AuthenticateResponse, _impl_.requestid_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::GaoProtobuf::AuthenticateRequest)},
        {10, -1, -1, sizeof(::GaoProtobuf::AuthenticateResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::GaoProtobuf::_AuthenticateRequest_default_instance_._instance,
    &::GaoProtobuf::_AuthenticateResponse_default_instance_._instance,
};
const char descriptor_table_protodef_Authenticate_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022Authenticate.proto\022\013GaoProtobuf\"7\n\023Aut"
    "henticateRequest\022\r\n\005token\030\001 \001(\t\022\021\n\treque"
    "stId\030\002 \001(\t\"\\\n\024AuthenticateResponse\0221\n\006re"
    "sult\030\001 \001(\0162!.GaoProtobuf.AuthenticationR"
    "esult\022\021\n\trequestId\030\002 \001(\t*@\n\024Authenticati"
    "onResult\022\013\n\007success\020\000\022\020\n\014unauthorized\020\001\022"
    "\t\n\005error\020\002B\016\252\002\013GaoProtobufb\006proto3"
};
static ::absl::once_flag descriptor_table_Authenticate_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Authenticate_2eproto = {
    false,
    false,
    274,
    descriptor_table_protodef_Authenticate_2eproto,
    "Authenticate.proto",
    &descriptor_table_Authenticate_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_Authenticate_2eproto::offsets,
    file_level_enum_descriptors_Authenticate_2eproto,
    file_level_service_descriptors_Authenticate_2eproto,
};
namespace GaoProtobuf {
const ::google::protobuf::EnumDescriptor* AuthenticationResult_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Authenticate_2eproto);
  return file_level_enum_descriptors_Authenticate_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t AuthenticationResult_internal_data_[] = {
    196608u, 0u, };
bool AuthenticationResult_IsValid(int value) {
  return 0 <= value && value <= 2;
}
// ===================================================================

class AuthenticateRequest::_Internal {
 public:
};

AuthenticateRequest::AuthenticateRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GaoProtobuf.AuthenticateRequest)
}
inline PROTOBUF_NDEBUG_INLINE AuthenticateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GaoProtobuf::AuthenticateRequest& from_msg)
      : token_(arena, from.token_),
        requestid_(arena, from.requestid_),
        _cached_size_{0} {}

AuthenticateRequest::AuthenticateRequest(
    ::google::protobuf::Arena* arena,
    const AuthenticateRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AuthenticateRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:GaoProtobuf.AuthenticateRequest)
}
inline PROTOBUF_NDEBUG_INLINE AuthenticateRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : token_(arena),
        requestid_(arena),
        _cached_size_{0} {}

inline void AuthenticateRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
AuthenticateRequest::~AuthenticateRequest() {
  // @@protoc_insertion_point(destructor:GaoProtobuf.AuthenticateRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AuthenticateRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.token_.Destroy();
  _impl_.requestid_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    AuthenticateRequest::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_AuthenticateRequest_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &AuthenticateRequest::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<AuthenticateRequest>(),
            ::google::protobuf::Message::GetNewImpl<AuthenticateRequest>(),
            ::google::protobuf::Message::GetClearImpl<AuthenticateRequest>(), &AuthenticateRequest::ByteSizeLong,
                &AuthenticateRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(AuthenticateRequest, _impl_._cached_size_),
            false,
        },
        &AuthenticateRequest::kDescriptorMethods,
        &descriptor_table_Authenticate_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* AuthenticateRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 54, 2> AuthenticateRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GaoProtobuf::AuthenticateRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string requestId = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(AuthenticateRequest, _impl_.requestid_)}},
    // string token = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(AuthenticateRequest, _impl_.token_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string token = 1;
    {PROTOBUF_FIELD_OFFSET(AuthenticateRequest, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string requestId = 2;
    {PROTOBUF_FIELD_OFFSET(AuthenticateRequest, _impl_.requestid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\37\5\11\0\0\0\0\0"
    "GaoProtobuf.AuthenticateRequest"
    "token"
    "requestId"
  }},
};

PROTOBUF_NOINLINE void AuthenticateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:GaoProtobuf.AuthenticateRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_.ClearToEmpty();
  _impl_.requestid_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* AuthenticateRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const AuthenticateRequest& this_ = static_cast<const AuthenticateRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* AuthenticateRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const AuthenticateRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GaoProtobuf.AuthenticateRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string token = 1;
          if (!this_._internal_token().empty()) {
            const std::string& _s = this_._internal_token();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GaoProtobuf.AuthenticateRequest.token");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string requestId = 2;
          if (!this_._internal_requestid().empty()) {
            const std::string& _s = this_._internal_requestid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GaoProtobuf.AuthenticateRequest.requestId");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GaoProtobuf.AuthenticateRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t AuthenticateRequest::ByteSizeLong(const MessageLite& base) {
          const AuthenticateRequest& this_ = static_cast<const AuthenticateRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t AuthenticateRequest::ByteSizeLong() const {
          const AuthenticateRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GaoProtobuf.AuthenticateRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string token = 1;
            if (!this_._internal_token().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_token());
            }
            // string requestId = 2;
            if (!this_._internal_requestid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_requestid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void AuthenticateRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AuthenticateRequest*>(&to_msg);
  auto& from = static_cast<const AuthenticateRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GaoProtobuf.AuthenticateRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (!from._internal_requestid().empty()) {
    _this->_internal_set_requestid(from._internal_requestid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthenticateRequest::CopyFrom(const AuthenticateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GaoProtobuf.AuthenticateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AuthenticateRequest::InternalSwap(AuthenticateRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.requestid_, &other->_impl_.requestid_, arena);
}

::google::protobuf::Metadata AuthenticateRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AuthenticateResponse::_Internal {
 public:
};

AuthenticateResponse::AuthenticateResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GaoProtobuf.AuthenticateResponse)
}
inline PROTOBUF_NDEBUG_INLINE AuthenticateResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GaoProtobuf::AuthenticateResponse& from_msg)
      : requestid_(arena, from.requestid_),
        _cached_size_{0} {}

AuthenticateResponse::AuthenticateResponse(
    ::google::protobuf::Arena* arena,
    const AuthenticateResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AuthenticateResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.result_ = from._impl_.result_;

  // @@protoc_insertion_point(copy_constructor:GaoProtobuf.AuthenticateResponse)
}
inline PROTOBUF_NDEBUG_INLINE AuthenticateResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : requestid_(arena),
        _cached_size_{0} {}

inline void AuthenticateResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.result_ = {};
}
AuthenticateResponse::~AuthenticateResponse() {
  // @@protoc_insertion_point(destructor:GaoProtobuf.AuthenticateResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AuthenticateResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.requestid_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    AuthenticateResponse::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_AuthenticateResponse_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &AuthenticateResponse::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<AuthenticateResponse>(),
            ::google::protobuf::Message::GetNewImpl<AuthenticateResponse>(),
            ::google::protobuf::Message::GetClearImpl<AuthenticateResponse>(), &AuthenticateResponse::ByteSizeLong,
                &AuthenticateResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(AuthenticateResponse, _impl_._cached_size_),
            false,
        },
        &AuthenticateResponse::kDescriptorMethods,
        &descriptor_table_Authenticate_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* AuthenticateResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 50, 2> AuthenticateResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GaoProtobuf::AuthenticateResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string requestId = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(AuthenticateResponse, _impl_.requestid_)}},
    // .GaoProtobuf.AuthenticationResult result = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AuthenticateResponse, _impl_.result_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(AuthenticateResponse, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .GaoProtobuf.AuthenticationResult result = 1;
    {PROTOBUF_FIELD_OFFSET(AuthenticateResponse, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string requestId = 2;
    {PROTOBUF_FIELD_OFFSET(AuthenticateResponse, _impl_.requestid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\40\0\11\0\0\0\0\0"
    "GaoProtobuf.AuthenticateResponse"
    "requestId"
  }},
};

PROTOBUF_NOINLINE void AuthenticateResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:GaoProtobuf.AuthenticateResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.requestid_.ClearToEmpty();
  _impl_.result_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* AuthenticateResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const AuthenticateResponse& this_ = static_cast<const AuthenticateResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* AuthenticateResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const AuthenticateResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GaoProtobuf.AuthenticateResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .GaoProtobuf.AuthenticationResult result = 1;
          if (this_._internal_result() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_result(), target);
          }

          // string requestId = 2;
          if (!this_._internal_requestid().empty()) {
            const std::string& _s = this_._internal_requestid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GaoProtobuf.AuthenticateResponse.requestId");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GaoProtobuf.AuthenticateResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t AuthenticateResponse::ByteSizeLong(const MessageLite& base) {
          const AuthenticateResponse& this_ = static_cast<const AuthenticateResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t AuthenticateResponse::ByteSizeLong() const {
          const AuthenticateResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GaoProtobuf.AuthenticateResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string requestId = 2;
            if (!this_._internal_requestid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_requestid());
            }
            // .GaoProtobuf.AuthenticationResult result = 1;
            if (this_._internal_result() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_result());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void AuthenticateResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AuthenticateResponse*>(&to_msg);
  auto& from = static_cast<const AuthenticateResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GaoProtobuf.AuthenticateResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_requestid().empty()) {
    _this->_internal_set_requestid(from._internal_requestid());
  }
  if (from._internal_result() != 0) {
    _this->_impl_.result_ = from._impl_.result_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthenticateResponse::CopyFrom(const AuthenticateResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GaoProtobuf.AuthenticateResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AuthenticateResponse::InternalSwap(AuthenticateResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.requestid_, &other->_impl_.requestid_, arena);
  swap(_impl_.result_, other->_impl_.result_);
}

::google::protobuf::Metadata AuthenticateResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace GaoProtobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Authenticate_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
