// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupBroadcast.proto

#include "GroupBroadcast.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace GaoProtobuf {
PROTOBUF_CONSTEXPR GroupDataChanged::GroupDataChanged(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.version_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GroupDataChangedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GroupDataChangedDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GroupDataChangedDefaultTypeInternal() {}
  union {
    GroupDataChanged _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GroupDataChangedDefaultTypeInternal _GroupDataChanged_default_instance_;
}  // namespace GaoProtobuf
static ::_pb::Metadata file_level_metadata_GroupBroadcast_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_GroupBroadcast_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_GroupBroadcast_2eproto = nullptr;

const uint32_t TableStruct_GroupBroadcast_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GaoProtobuf::GroupDataChanged, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::GaoProtobuf::GroupDataChanged, _impl_.version_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::GaoProtobuf::GroupDataChanged)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::GaoProtobuf::_GroupDataChanged_default_instance_._instance,
};

const char descriptor_table_protodef_GroupBroadcast_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024GroupBroadcast.proto\022\013GaoProtobuf\"#\n\020G"
  "roupDataChanged\022\017\n\007version\030\001 \001(\003B\016\252\002\013Gao"
  "Protobufb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_GroupBroadcast_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_GroupBroadcast_2eproto = {
    false, false, 96, descriptor_table_protodef_GroupBroadcast_2eproto,
    "GroupBroadcast.proto",
    &descriptor_table_GroupBroadcast_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_GroupBroadcast_2eproto::offsets,
    file_level_metadata_GroupBroadcast_2eproto, file_level_enum_descriptors_GroupBroadcast_2eproto,
    file_level_service_descriptors_GroupBroadcast_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_GroupBroadcast_2eproto_getter() {
  return &descriptor_table_GroupBroadcast_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_GroupBroadcast_2eproto(&descriptor_table_GroupBroadcast_2eproto);
namespace GaoProtobuf {

// ===================================================================

class GroupDataChanged::_Internal {
 public:
};

GroupDataChanged::GroupDataChanged(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:GaoProtobuf.GroupDataChanged)
}
GroupDataChanged::GroupDataChanged(const GroupDataChanged& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GroupDataChanged* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.version_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.version_ = from._impl_.version_;
  // @@protoc_insertion_point(copy_constructor:GaoProtobuf.GroupDataChanged)
}

inline void GroupDataChanged::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.version_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GroupDataChanged::~GroupDataChanged() {
  // @@protoc_insertion_point(destructor:GaoProtobuf.GroupDataChanged)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GroupDataChanged::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void GroupDataChanged::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GroupDataChanged::Clear() {
// @@protoc_insertion_point(message_clear_start:GaoProtobuf.GroupDataChanged)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.version_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GroupDataChanged::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 version = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GroupDataChanged::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GaoProtobuf.GroupDataChanged)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 version = 1;
  if (this->_internal_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_version(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GaoProtobuf.GroupDataChanged)
  return target;
}

size_t GroupDataChanged::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GaoProtobuf.GroupDataChanged)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 version = 1;
  if (this->_internal_version() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_version());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GroupDataChanged::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GroupDataChanged::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GroupDataChanged::GetClassData() const { return &_class_data_; }


void GroupDataChanged::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GroupDataChanged*>(&to_msg);
  auto& from = static_cast<const GroupDataChanged&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GaoProtobuf.GroupDataChanged)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_version() != 0) {
    _this->_internal_set_version(from._internal_version());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GroupDataChanged::CopyFrom(const GroupDataChanged& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GaoProtobuf.GroupDataChanged)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GroupDataChanged::IsInitialized() const {
  return true;
}

void GroupDataChanged::InternalSwap(GroupDataChanged* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.version_, other->_impl_.version_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GroupDataChanged::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_GroupBroadcast_2eproto_getter, &descriptor_table_GroupBroadcast_2eproto_once,
      file_level_metadata_GroupBroadcast_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace GaoProtobuf
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::GaoProtobuf::GroupDataChanged*
Arena::CreateMaybeMessage< ::GaoProtobuf::GroupDataChanged >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GaoProtobuf::GroupDataChanged >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
