// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: GroupBroadcast.proto
// Protobuf C++ Version: 5.28.2

#include "GroupBroadcast.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace GaoProtobuf {

inline constexpr GroupDataChanged::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : version_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GroupDataChanged::GroupDataChanged(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GroupDataChangedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GroupDataChangedDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GroupDataChangedDefaultTypeInternal() {}
  union {
    GroupDataChanged _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GroupDataChangedDefaultTypeInternal _GroupDataChanged_default_instance_;
}  // namespace GaoProtobuf
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_GroupBroadcast_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_GroupBroadcast_2eproto = nullptr;
const ::uint32_t
    TableStruct_GroupBroadcast_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GaoProtobuf::GroupDataChanged, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GaoProtobuf::GroupDataChanged, _impl_.version_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::GaoProtobuf::GroupDataChanged)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::GaoProtobuf::_GroupDataChanged_default_instance_._instance,
};
const char descriptor_table_protodef_GroupBroadcast_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024GroupBroadcast.proto\022\013GaoProtobuf\"#\n\020G"
    "roupDataChanged\022\017\n\007version\030\001 \001(\003B\016\252\002\013Gao"
    "Protobufb\006proto3"
};
static ::absl::once_flag descriptor_table_GroupBroadcast_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_GroupBroadcast_2eproto = {
    false,
    false,
    96,
    descriptor_table_protodef_GroupBroadcast_2eproto,
    "GroupBroadcast.proto",
    &descriptor_table_GroupBroadcast_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_GroupBroadcast_2eproto::offsets,
    file_level_enum_descriptors_GroupBroadcast_2eproto,
    file_level_service_descriptors_GroupBroadcast_2eproto,
};
namespace GaoProtobuf {
// ===================================================================

class GroupDataChanged::_Internal {
 public:
};

GroupDataChanged::GroupDataChanged(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GaoProtobuf.GroupDataChanged)
}
GroupDataChanged::GroupDataChanged(
    ::google::protobuf::Arena* arena, const GroupDataChanged& from)
    : GroupDataChanged(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE GroupDataChanged::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GroupDataChanged::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.version_ = {};
}
GroupDataChanged::~GroupDataChanged() {
  // @@protoc_insertion_point(destructor:GaoProtobuf.GroupDataChanged)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void GroupDataChanged::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    GroupDataChanged::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_GroupDataChanged_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &GroupDataChanged::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<GroupDataChanged>(),
            ::google::protobuf::Message::GetNewImpl<GroupDataChanged>(),
            ::google::protobuf::Message::GetClearImpl<GroupDataChanged>(), &GroupDataChanged::ByteSizeLong,
                &GroupDataChanged::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(GroupDataChanged, _impl_._cached_size_),
            false,
        },
        &GroupDataChanged::kDescriptorMethods,
        &descriptor_table_GroupBroadcast_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* GroupDataChanged::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> GroupDataChanged::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GaoProtobuf::GroupDataChanged>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 version = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(GroupDataChanged, _impl_.version_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GroupDataChanged, _impl_.version_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 version = 1;
    {PROTOBUF_FIELD_OFFSET(GroupDataChanged, _impl_.version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GroupDataChanged::Clear() {
// @@protoc_insertion_point(message_clear_start:GaoProtobuf.GroupDataChanged)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.version_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GroupDataChanged::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GroupDataChanged& this_ = static_cast<const GroupDataChanged&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GroupDataChanged::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GroupDataChanged& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GaoProtobuf.GroupDataChanged)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int64 version = 1;
          if (this_._internal_version() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<1>(
                    stream, this_._internal_version(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GaoProtobuf.GroupDataChanged)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GroupDataChanged::ByteSizeLong(const MessageLite& base) {
          const GroupDataChanged& this_ = static_cast<const GroupDataChanged&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GroupDataChanged::ByteSizeLong() const {
          const GroupDataChanged& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GaoProtobuf.GroupDataChanged)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int64 version = 1;
            if (this_._internal_version() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_version());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GroupDataChanged::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GroupDataChanged*>(&to_msg);
  auto& from = static_cast<const GroupDataChanged&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GaoProtobuf.GroupDataChanged)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_version() != 0) {
    _this->_impl_.version_ = from._impl_.version_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GroupDataChanged::CopyFrom(const GroupDataChanged& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GaoProtobuf.GroupDataChanged)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GroupDataChanged::InternalSwap(GroupDataChanged* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.version_, other->_impl_.version_);
}

::google::protobuf::Metadata GroupDataChanged::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace GaoProtobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_GroupBroadcast_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
