// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MessageHeader.proto
// Protobuf C++ Version: 5.28.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_MessageHeader_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_MessageHeader_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_MessageHeader_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_MessageHeader_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_MessageHeader_2eproto;
namespace GaoProtobuf {
class MessageHeader;
struct MessageHeaderDefaultTypeInternal;
extern MessageHeaderDefaultTypeInternal _MessageHeader_default_instance_;
}  // namespace GaoProtobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace GaoProtobuf {

// ===================================================================


// -------------------------------------------------------------------

class MessageHeader final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:GaoProtobuf.MessageHeader) */ {
 public:
  inline MessageHeader() : MessageHeader(nullptr) {}
  ~MessageHeader() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MessageHeader(
      ::google::protobuf::internal::ConstantInitialized);

  inline MessageHeader(const MessageHeader& from) : MessageHeader(nullptr, from) {}
  inline MessageHeader(MessageHeader&& from) noexcept
      : MessageHeader(nullptr, std::move(from)) {}
  inline MessageHeader& operator=(const MessageHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline MessageHeader& operator=(MessageHeader&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MessageHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const MessageHeader* internal_default_instance() {
    return reinterpret_cast<const MessageHeader*>(
        &_MessageHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MessageHeader& a, MessageHeader& b) { a.Swap(&b); }
  inline void Swap(MessageHeader* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MessageHeader* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MessageHeader* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<MessageHeader>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MessageHeader& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MessageHeader& from) { MessageHeader::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(MessageHeader* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "GaoProtobuf.MessageHeader"; }

 protected:
  explicit MessageHeader(::google::protobuf::Arena* arena);
  MessageHeader(::google::protobuf::Arena* arena, const MessageHeader& from);
  MessageHeader(::google::protobuf::Arena* arena, MessageHeader&& from) noexcept
      : MessageHeader(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFromIdFieldNumber = 1,
    kToIdFieldNumber = 2,
    kGroupIdFieldNumber = 3,
    kTypeIdFieldNumber = 4,
    kNamespaceIdFieldNumber = 5,
    kClassIdFieldNumber = 6,
    kMethodIdFieldNumber = 7,
  };
  // int32 fromId = 1;
  void clear_fromid() ;
  ::int32_t fromid() const;
  void set_fromid(::int32_t value);

  private:
  ::int32_t _internal_fromid() const;
  void _internal_set_fromid(::int32_t value);

  public:
  // int32 toId = 2;
  void clear_toid() ;
  ::int32_t toid() const;
  void set_toid(::int32_t value);

  private:
  ::int32_t _internal_toid() const;
  void _internal_set_toid(::int32_t value);

  public:
  // int32 groupId = 3;
  void clear_groupid() ;
  ::int32_t groupid() const;
  void set_groupid(::int32_t value);

  private:
  ::int32_t _internal_groupid() const;
  void _internal_set_groupid(::int32_t value);

  public:
  // int32 typeId = 4;
  void clear_typeid_() ;
  ::int32_t typeid_() const;
  void set_typeid_(::int32_t value);

  private:
  ::int32_t _internal_typeid_() const;
  void _internal_set_typeid_(::int32_t value);

  public:
  // int32 namespaceId = 5;
  void clear_namespaceid() ;
  ::int32_t namespaceid() const;
  void set_namespaceid(::int32_t value);

  private:
  ::int32_t _internal_namespaceid() const;
  void _internal_set_namespaceid(::int32_t value);

  public:
  // int32 classId = 6;
  void clear_classid() ;
  ::int32_t classid() const;
  void set_classid(::int32_t value);

  private:
  ::int32_t _internal_classid() const;
  void _internal_set_classid(::int32_t value);

  public:
  // int32 methodId = 7;
  void clear_methodid() ;
  ::int32_t methodid() const;
  void set_methodid(::int32_t value);

  private:
  ::int32_t _internal_methodid() const;
  void _internal_set_methodid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:GaoProtobuf.MessageHeader)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_MessageHeader_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MessageHeader& from_msg);
    ::int32_t fromid_;
    ::int32_t toid_;
    ::int32_t groupid_;
    ::int32_t typeid__;
    ::int32_t namespaceid_;
    ::int32_t classid_;
    ::int32_t methodid_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MessageHeader_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MessageHeader

// int32 fromId = 1;
inline void MessageHeader::clear_fromid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fromid_ = 0;
}
inline ::int32_t MessageHeader::fromid() const {
  // @@protoc_insertion_point(field_get:GaoProtobuf.MessageHeader.fromId)
  return _internal_fromid();
}
inline void MessageHeader::set_fromid(::int32_t value) {
  _internal_set_fromid(value);
  // @@protoc_insertion_point(field_set:GaoProtobuf.MessageHeader.fromId)
}
inline ::int32_t MessageHeader::_internal_fromid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fromid_;
}
inline void MessageHeader::_internal_set_fromid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fromid_ = value;
}

// int32 toId = 2;
inline void MessageHeader::clear_toid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.toid_ = 0;
}
inline ::int32_t MessageHeader::toid() const {
  // @@protoc_insertion_point(field_get:GaoProtobuf.MessageHeader.toId)
  return _internal_toid();
}
inline void MessageHeader::set_toid(::int32_t value) {
  _internal_set_toid(value);
  // @@protoc_insertion_point(field_set:GaoProtobuf.MessageHeader.toId)
}
inline ::int32_t MessageHeader::_internal_toid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.toid_;
}
inline void MessageHeader::_internal_set_toid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.toid_ = value;
}

// int32 groupId = 3;
inline void MessageHeader::clear_groupid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.groupid_ = 0;
}
inline ::int32_t MessageHeader::groupid() const {
  // @@protoc_insertion_point(field_get:GaoProtobuf.MessageHeader.groupId)
  return _internal_groupid();
}
inline void MessageHeader::set_groupid(::int32_t value) {
  _internal_set_groupid(value);
  // @@protoc_insertion_point(field_set:GaoProtobuf.MessageHeader.groupId)
}
inline ::int32_t MessageHeader::_internal_groupid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.groupid_;
}
inline void MessageHeader::_internal_set_groupid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.groupid_ = value;
}

// int32 typeId = 4;
inline void MessageHeader::clear_typeid_() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typeid__ = 0;
}
inline ::int32_t MessageHeader::typeid_() const {
  // @@protoc_insertion_point(field_get:GaoProtobuf.MessageHeader.typeId)
  return _internal_typeid_();
}
inline void MessageHeader::set_typeid_(::int32_t value) {
  _internal_set_typeid_(value);
  // @@protoc_insertion_point(field_set:GaoProtobuf.MessageHeader.typeId)
}
inline ::int32_t MessageHeader::_internal_typeid_() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.typeid__;
}
inline void MessageHeader::_internal_set_typeid_(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typeid__ = value;
}

// int32 namespaceId = 5;
inline void MessageHeader::clear_namespaceid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.namespaceid_ = 0;
}
inline ::int32_t MessageHeader::namespaceid() const {
  // @@protoc_insertion_point(field_get:GaoProtobuf.MessageHeader.namespaceId)
  return _internal_namespaceid();
}
inline void MessageHeader::set_namespaceid(::int32_t value) {
  _internal_set_namespaceid(value);
  // @@protoc_insertion_point(field_set:GaoProtobuf.MessageHeader.namespaceId)
}
inline ::int32_t MessageHeader::_internal_namespaceid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.namespaceid_;
}
inline void MessageHeader::_internal_set_namespaceid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.namespaceid_ = value;
}

// int32 classId = 6;
inline void MessageHeader::clear_classid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.classid_ = 0;
}
inline ::int32_t MessageHeader::classid() const {
  // @@protoc_insertion_point(field_get:GaoProtobuf.MessageHeader.classId)
  return _internal_classid();
}
inline void MessageHeader::set_classid(::int32_t value) {
  _internal_set_classid(value);
  // @@protoc_insertion_point(field_set:GaoProtobuf.MessageHeader.classId)
}
inline ::int32_t MessageHeader::_internal_classid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.classid_;
}
inline void MessageHeader::_internal_set_classid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.classid_ = value;
}

// int32 methodId = 7;
inline void MessageHeader::clear_methodid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.methodid_ = 0;
}
inline ::int32_t MessageHeader::methodid() const {
  // @@protoc_insertion_point(field_get:GaoProtobuf.MessageHeader.methodId)
  return _internal_methodid();
}
inline void MessageHeader::set_methodid(::int32_t value) {
  _internal_set_methodid(value);
  // @@protoc_insertion_point(field_set:GaoProtobuf.MessageHeader.methodId)
}
inline ::int32_t MessageHeader::_internal_methodid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.methodid_;
}
inline void MessageHeader::_internal_set_methodid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.methodid_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace GaoProtobuf


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_MessageHeader_2eproto_2epb_2eh
