// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageHeader.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MessageHeader_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MessageHeader_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MessageHeader_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MessageHeader_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MessageHeader_2eproto;
namespace GaoProtobuf {
class MessageHeader;
struct MessageHeaderDefaultTypeInternal;
extern MessageHeaderDefaultTypeInternal _MessageHeader_default_instance_;
}  // namespace GaoProtobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::GaoProtobuf::MessageHeader* Arena::CreateMaybeMessage<::GaoProtobuf::MessageHeader>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace GaoProtobuf {

// ===================================================================

class MessageHeader final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GaoProtobuf.MessageHeader) */ {
 public:
  inline MessageHeader() : MessageHeader(nullptr) {}
  ~MessageHeader() override;
  explicit PROTOBUF_CONSTEXPR MessageHeader(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MessageHeader(const MessageHeader& from);
  MessageHeader(MessageHeader&& from) noexcept
    : MessageHeader() {
    *this = ::std::move(from);
  }

  inline MessageHeader& operator=(const MessageHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline MessageHeader& operator=(MessageHeader&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MessageHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const MessageHeader* internal_default_instance() {
    return reinterpret_cast<const MessageHeader*>(
               &_MessageHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MessageHeader& a, MessageHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(MessageHeader* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MessageHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MessageHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MessageHeader>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MessageHeader& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const MessageHeader& from) {
    MessageHeader::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MessageHeader* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GaoProtobuf.MessageHeader";
  }
  protected:
  explicit MessageHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFromFieldNumber = 1,
    kToFieldNumber = 2,
    kGroupFieldNumber = 3,
    kTypeFieldNumber = 4,
    kNamespaceFieldNumber = 5,
    kClasssFieldNumber = 6,
    kMethodFieldNumber = 7,
  };
  // int64 from = 1;
  void clear_from();
  int64_t from() const;
  void set_from(int64_t value);
  private:
  int64_t _internal_from() const;
  void _internal_set_from(int64_t value);
  public:

  // int64 to = 2;
  void clear_to();
  int64_t to() const;
  void set_to(int64_t value);
  private:
  int64_t _internal_to() const;
  void _internal_set_to(int64_t value);
  public:

  // int64 group = 3;
  void clear_group();
  int64_t group() const;
  void set_group(int64_t value);
  private:
  int64_t _internal_group() const;
  void _internal_set_group(int64_t value);
  public:

  // int32 type = 4;
  void clear_type();
  int32_t type() const;
  void set_type(int32_t value);
  private:
  int32_t _internal_type() const;
  void _internal_set_type(int32_t value);
  public:

  // int32 namespace = 5;
  void clear_namespace_();
  int32_t namespace_() const;
  void set_namespace_(int32_t value);
  private:
  int32_t _internal_namespace_() const;
  void _internal_set_namespace_(int32_t value);
  public:

  // int32 classs = 6;
  void clear_classs();
  int32_t classs() const;
  void set_classs(int32_t value);
  private:
  int32_t _internal_classs() const;
  void _internal_set_classs(int32_t value);
  public:

  // int32 method = 7;
  void clear_method();
  int32_t method() const;
  void set_method(int32_t value);
  private:
  int32_t _internal_method() const;
  void _internal_set_method(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:GaoProtobuf.MessageHeader)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t from_;
    int64_t to_;
    int64_t group_;
    int32_t type_;
    int32_t namespace__;
    int32_t classs_;
    int32_t method_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_MessageHeader_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MessageHeader

// int64 from = 1;
inline void MessageHeader::clear_from() {
  _impl_.from_ = int64_t{0};
}
inline int64_t MessageHeader::_internal_from() const {
  return _impl_.from_;
}
inline int64_t MessageHeader::from() const {
  // @@protoc_insertion_point(field_get:GaoProtobuf.MessageHeader.from)
  return _internal_from();
}
inline void MessageHeader::_internal_set_from(int64_t value) {
  
  _impl_.from_ = value;
}
inline void MessageHeader::set_from(int64_t value) {
  _internal_set_from(value);
  // @@protoc_insertion_point(field_set:GaoProtobuf.MessageHeader.from)
}

// int64 to = 2;
inline void MessageHeader::clear_to() {
  _impl_.to_ = int64_t{0};
}
inline int64_t MessageHeader::_internal_to() const {
  return _impl_.to_;
}
inline int64_t MessageHeader::to() const {
  // @@protoc_insertion_point(field_get:GaoProtobuf.MessageHeader.to)
  return _internal_to();
}
inline void MessageHeader::_internal_set_to(int64_t value) {
  
  _impl_.to_ = value;
}
inline void MessageHeader::set_to(int64_t value) {
  _internal_set_to(value);
  // @@protoc_insertion_point(field_set:GaoProtobuf.MessageHeader.to)
}

// int64 group = 3;
inline void MessageHeader::clear_group() {
  _impl_.group_ = int64_t{0};
}
inline int64_t MessageHeader::_internal_group() const {
  return _impl_.group_;
}
inline int64_t MessageHeader::group() const {
  // @@protoc_insertion_point(field_get:GaoProtobuf.MessageHeader.group)
  return _internal_group();
}
inline void MessageHeader::_internal_set_group(int64_t value) {
  
  _impl_.group_ = value;
}
inline void MessageHeader::set_group(int64_t value) {
  _internal_set_group(value);
  // @@protoc_insertion_point(field_set:GaoProtobuf.MessageHeader.group)
}

// int32 type = 4;
inline void MessageHeader::clear_type() {
  _impl_.type_ = 0;
}
inline int32_t MessageHeader::_internal_type() const {
  return _impl_.type_;
}
inline int32_t MessageHeader::type() const {
  // @@protoc_insertion_point(field_get:GaoProtobuf.MessageHeader.type)
  return _internal_type();
}
inline void MessageHeader::_internal_set_type(int32_t value) {
  
  _impl_.type_ = value;
}
inline void MessageHeader::set_type(int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:GaoProtobuf.MessageHeader.type)
}

// int32 namespace = 5;
inline void MessageHeader::clear_namespace_() {
  _impl_.namespace__ = 0;
}
inline int32_t MessageHeader::_internal_namespace_() const {
  return _impl_.namespace__;
}
inline int32_t MessageHeader::namespace_() const {
  // @@protoc_insertion_point(field_get:GaoProtobuf.MessageHeader.namespace)
  return _internal_namespace_();
}
inline void MessageHeader::_internal_set_namespace_(int32_t value) {
  
  _impl_.namespace__ = value;
}
inline void MessageHeader::set_namespace_(int32_t value) {
  _internal_set_namespace_(value);
  // @@protoc_insertion_point(field_set:GaoProtobuf.MessageHeader.namespace)
}

// int32 classs = 6;
inline void MessageHeader::clear_classs() {
  _impl_.classs_ = 0;
}
inline int32_t MessageHeader::_internal_classs() const {
  return _impl_.classs_;
}
inline int32_t MessageHeader::classs() const {
  // @@protoc_insertion_point(field_get:GaoProtobuf.MessageHeader.classs)
  return _internal_classs();
}
inline void MessageHeader::_internal_set_classs(int32_t value) {
  
  _impl_.classs_ = value;
}
inline void MessageHeader::set_classs(int32_t value) {
  _internal_set_classs(value);
  // @@protoc_insertion_point(field_set:GaoProtobuf.MessageHeader.classs)
}

// int32 method = 7;
inline void MessageHeader::clear_method() {
  _impl_.method_ = 0;
}
inline int32_t MessageHeader::_internal_method() const {
  return _impl_.method_;
}
inline int32_t MessageHeader::method() const {
  // @@protoc_insertion_point(field_get:GaoProtobuf.MessageHeader.method)
  return _internal_method();
}
inline void MessageHeader::_internal_set_method(int32_t value) {
  
  _impl_.method_ = value;
}
inline void MessageHeader::set_method(int32_t value) {
  _internal_set_method(value);
  // @@protoc_insertion_point(field_set:GaoProtobuf.MessageHeader.method)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace GaoProtobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MessageHeader_2eproto
