// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gaos/GroupCreditsChange.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_gaos_2fGroupCreditsChange_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_gaos_2fGroupCreditsChange_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_gaos_2fGroupCreditsChange_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_gaos_2fGroupCreditsChange_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_gaos_2fGroupCreditsChange_2eproto;
namespace GaoProtobuf {
namespace gaos {
class GroupCreditsChange;
struct GroupCreditsChangeDefaultTypeInternal;
extern GroupCreditsChangeDefaultTypeInternal _GroupCreditsChange_default_instance_;
}  // namespace gaos
}  // namespace GaoProtobuf
PROTOBUF_NAMESPACE_OPEN
template<> ::GaoProtobuf::gaos::GroupCreditsChange* Arena::CreateMaybeMessage<::GaoProtobuf::gaos::GroupCreditsChange>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace GaoProtobuf {
namespace gaos {

// ===================================================================

class GroupCreditsChange final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GaoProtobuf.gaos.GroupCreditsChange) */ {
 public:
  inline GroupCreditsChange() : GroupCreditsChange(nullptr) {}
  ~GroupCreditsChange() override;
  explicit PROTOBUF_CONSTEXPR GroupCreditsChange(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GroupCreditsChange(const GroupCreditsChange& from);
  GroupCreditsChange(GroupCreditsChange&& from) noexcept
    : GroupCreditsChange() {
    *this = ::std::move(from);
  }

  inline GroupCreditsChange& operator=(const GroupCreditsChange& from) {
    CopyFrom(from);
    return *this;
  }
  inline GroupCreditsChange& operator=(GroupCreditsChange&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GroupCreditsChange& default_instance() {
    return *internal_default_instance();
  }
  static inline const GroupCreditsChange* internal_default_instance() {
    return reinterpret_cast<const GroupCreditsChange*>(
               &_GroupCreditsChange_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GroupCreditsChange& a, GroupCreditsChange& b) {
    a.Swap(&b);
  }
  inline void Swap(GroupCreditsChange* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GroupCreditsChange* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GroupCreditsChange* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GroupCreditsChange>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GroupCreditsChange& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GroupCreditsChange& from) {
    GroupCreditsChange::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GroupCreditsChange* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GaoProtobuf.gaos.GroupCreditsChange";
  }
  protected:
  explicit GroupCreditsChange(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUserIdFieldNumber = 1,
  };
  // int64 userId = 1;
  void clear_userid();
  int64_t userid() const;
  void set_userid(int64_t value);
  private:
  int64_t _internal_userid() const;
  void _internal_set_userid(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:GaoProtobuf.gaos.GroupCreditsChange)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t userid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_gaos_2fGroupCreditsChange_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GroupCreditsChange

// int64 userId = 1;
inline void GroupCreditsChange::clear_userid() {
  _impl_.userid_ = int64_t{0};
}
inline int64_t GroupCreditsChange::_internal_userid() const {
  return _impl_.userid_;
}
inline int64_t GroupCreditsChange::userid() const {
  // @@protoc_insertion_point(field_get:GaoProtobuf.gaos.GroupCreditsChange.userId)
  return _internal_userid();
}
inline void GroupCreditsChange::_internal_set_userid(int64_t value) {
  
  _impl_.userid_ = value;
}
inline void GroupCreditsChange::set_userid(int64_t value) {
  _internal_set_userid(value);
  // @@protoc_insertion_point(field_set:GaoProtobuf.gaos.GroupCreditsChange.userId)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace gaos
}  // namespace GaoProtobuf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_gaos_2fGroupCreditsChange_2eproto
